/*
*   系统常设定
*/
//消息提示时间(短)
const MESSAGE_DISSMISS_TIME_SHORT=500;
//消息提示时间(短)
const MESSAGE_DISSMISS_TIME_MID=1000;
//消息提示时间(长)
const MESSAGE_DISSMISS_TIME_LONG=3000;
const COMPANY_TYPE_STALL=1;
const COMPANY_TYPE_SALER=2;
const SETTING_AUTH_NAME="AUTH_";




export default
{
 	MESSAGE_DISSMISS_TIME_SHORT,
 	MESSAGE_DISSMISS_TIME_MID,
 	MESSAGE_DISSMISS_TIME_LONG,
 	COMPANY_TYPE_STALL,
 	COMPANY_TYPE_SALER,
    SETTING_AUTH_NAME
}
